
import { jsPDF } from 'jspdf';
import { ReportData } from './reportGenerator';

export class FileGenerator {
  static async generatePDF(report: ReportData): Promise<Blob> {
    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.width;
    const margin = 20;
    const lineHeight = 7;
    let yPosition = margin;

    // Add title
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    const titleLines = pdf.splitTextToSize(report.title, pageWidth - 2 * margin);
    pdf.text(titleLines, margin, yPosition);
    yPosition += titleLines.length * lineHeight + 10;

    // Add metadata
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Generated on ${report.generatedAt.toLocaleDateString()} at ${report.generatedAt.toLocaleTimeString()}`, margin, yPosition);
    yPosition += lineHeight + 10;

    // Clean and format content for PDF
    const cleanContent = this.convertHTMLToText(report.content);
    pdf.setFontSize(11);
    const contentLines = pdf.splitTextToSize(cleanContent, pageWidth - 2 * margin);
    
    for (let i = 0; i < contentLines.length; i++) {
      if (yPosition > pdf.internal.pageSize.height - margin) {
        pdf.addPage();
        yPosition = margin;
      }
      pdf.text(contentLines[i], margin, yPosition);
      yPosition += lineHeight;
    }

    return pdf.output('blob');
  }

  static async generateHTML(report: ReportData): Promise<Blob> {
    const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${report.title}</title>
    <style>
        body { 
            font-family: 'Georgia', serif; 
            max-width: 800px; 
            margin: 0 auto; 
            padding: 2rem; 
            line-height: 1.8;
            color: #2c3e50;
            background: #fafafa;
        }
        .header {
            border-bottom: 3px solid #DAA520;
            padding-bottom: 1rem;
            margin-bottom: 2rem;
        }
        h1 { 
            color: #1e293b; 
            font-size: 2.2rem;
            margin-bottom: 0.5rem;
        }
        .meta { 
            color: #64748b; 
            font-size: 0.9rem; 
            font-style: italic;
        }
        .content {
            white-space: pre-line;
            font-size: 1.1rem;
            line-height: 1.8;
        }
        h2 { 
            color: #DAA520; 
            border-bottom: 1px solid #DAA520;
            padding-bottom: 0.3rem;
            margin-top: 2rem;
        }
        h3 { 
            color: #1e293b; 
            margin-top: 1.5rem;
        }
        ul, ol {
            margin: 1rem 0;
            padding-left: 2rem;
        }
        li {
            margin: 0.5rem 0;
        }
        .footer {
            margin-top: 3rem;
            padding-top: 1rem;
            border-top: 1px solid #e2e8f0;
            text-align: center;
            color: #64748b;
            font-size: 0.8rem;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>${report.title}</h1>
        <div class="meta">Generated on ${report.generatedAt.toLocaleDateString()} at ${report.generatedAt.toLocaleTimeString()}</div>
    </div>
    <div class="content">${this.formatContentAsHTML(report.content)}</div>
    <div class="footer">
        Generated by AGORA - The Eternal Space for Collective Wisdom
    </div>
</body>
</html>`;
    
    return new Blob([htmlContent], { type: 'text/html' });
  }

  static downloadFile(blob: Blob, filename: string, format: string) {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${filename}.${format}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  // Convert HTML content to clean text for PDF generation
  private static convertHTMLToText(htmlContent: string): string {
    // Remove HTML tags and convert to plain text
    let text = htmlContent
      // Remove HTML tags but preserve content
      .replace(/<[^>]*>/g, '')
      // Convert HTML entities
      .replace(/&nbsp;/g, ' ')
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      // Handle markdown-style formatting
      .replace(/^#{1,3}\s+(.+)$/gm, '\n$1\n')  // Convert headings
      .replace(/\*\*(.*?)\*\*/g, '$1')         // Remove bold markers
      .replace(/\*(.*?)\*/g, '$1')             // Remove italic markers
      // Clean up extra whitespace
      .replace(/\n{3,}/g, '\n\n')             // Max 2 consecutive newlines
      .replace(/[ \t]+/g, ' ')                // Multiple spaces to single space
      .trim();

    return text;
  }

  // Enhanced HTML formatting for rich HTML export
  private static formatContentAsHTML(content: string): string {
    return content
      .replace(/^# (.*$)/gm, '<h2>$1</h2>')
      .replace(/^## (.*$)/gm, '<h3>$1</h3>')
      .replace(/^### (.*$)/gm, '<h4>$1</h4>')
      .replace(/^\- (.*$)/gm, '<li>$1</li>')
      .replace(/(<li>.*<\/li>)/s, '<ul>$1</ul>')
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>')
      .replace(/\n\n/g, '</p><p>')
      .replace(/^(?!<[hul])/gm, '<p>')
      .replace(/(?<!>)$/gm, '</p>');
  }

  // Create PDF-specific branding content
  static createPDFBrandingContent(title: string, generatedAt: Date, expertCount: number, messageCount: number, challenge: string): string {
    return `
AGORA - Collective Minds & Wisdom Platform

Report: ${title}
Generated: ${generatedAt.toLocaleDateString()} at ${generatedAt.toLocaleTimeString()}

Expert Voices: ${expertCount}
Total Insights: ${messageCount}
Challenge: ${challenge}

========================================

`;
  }

  // Create HTML-specific enhanced content with rich formatting
  static createHTMLBrandingContent(title: string, generatedAt: Date, expertCount: number, messageCount: number, challenge: string): string {
    return `
      <div style="margin-bottom: 30px;">
        <div style="background: linear-gradient(135deg, #4F46E5 0%, #7C3AED 100%); color: white; padding: 30px; border-radius: 8px 8px 0 0;">
          <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;">
            <div style="display: flex; align-items: center; gap: 15px;">
              <div style="width: 40px; height: 40px; background: white; border-radius: 50%; display: flex; align-items: center; justify-content: center;">
                <span style="color: #4F46E5; font-weight: bold; font-size: 18px;">A</span>
              </div>
              <div>
                <h1 style="margin: 0; font-size: 24px; font-weight: bold;">AGORA</h1>
                <p style="margin: 0; font-size: 14px; opacity: 0.8;">Collective Minds & Wisdom</p>
              </div>
            </div>
            <div style="text-align: right; font-size: 12px; opacity: 0.8;">
              <p style="margin: 0;">Generated: ${generatedAt.toLocaleDateString()}</p>
              <p style="margin: 0;">${generatedAt.toLocaleTimeString()}</p>
            </div>
          </div>
          <div style="border-top: 1px solid rgba(255,255,255,0.3); padding-top: 20px;">
            <h2 style="margin: 0 0 10px 0; font-size: 28px; font-weight: bold;">${title}</h2>
            <div style="display: flex; gap: 30px; font-size: 13px;">
              <div><span style="opacity: 0.8;">Expert Voices:</span> <span style="font-weight: bold;">${expertCount}</span></div>
              <div><span style="opacity: 0.8;">Insights:</span> <span style="font-weight: bold;">${messageCount}</span></div>
              <div><span style="opacity: 0.8;">Challenge:</span> <span style="font-weight: bold;">${challenge}</span></div>
            </div>
          </div>
        </div>
      </div>`;
  }
}
