
import { jsPDF } from 'jspdf';
import { ReportData } from './reportGenerator';

export class FileGenerator {
  static async generatePDF(report: ReportData): Promise<Blob> {
    const pdf = new jsPDF();
    const pageWidth = pdf.internal.pageSize.width;
    const margin = 20;
    const lineHeight = 7;
    let yPosition = margin;

    // Add title
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    const titleLines = pdf.splitTextToSize(report.title, pageWidth - 2 * margin);
    pdf.text(titleLines, margin, yPosition);
    yPosition += titleLines.length * lineHeight + 10;

    // Add metadata
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Generated on ${report.generatedAt.toLocaleDateString()} at ${report.generatedAt.toLocaleTimeString()}`, margin, yPosition);
    yPosition += lineHeight + 10;

    // Add content
    pdf.setFontSize(11);
    const contentLines = pdf.splitTextToSize(report.content, pageWidth - 2 * margin);
    
    for (let i = 0; i < contentLines.length; i++) {
      if (yPosition > pdf.internal.pageSize.height - margin) {
        pdf.addPage();
        yPosition = margin;
      }
      pdf.text(contentLines[i], margin, yPosition);
      yPosition += lineHeight;
    }

    return pdf.output('blob');
  }

  static async generateHTML(report: ReportData): Promise<Blob> {
    const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${report.title}</title>
    <style>
        body { 
            font-family: 'Georgia', serif; 
            max-width: 800px; 
            margin: 0 auto; 
            padding: 2rem; 
            line-height: 1.8;
            color: #2c3e50;
            background: #fafafa;
        }
        .header {
            border-bottom: 3px solid #DAA520;
            padding-bottom: 1rem;
            margin-bottom: 2rem;
        }
        h1 { 
            color: #1e293b; 
            font-size: 2.2rem;
            margin-bottom: 0.5rem;
        }
        .meta { 
            color: #64748b; 
            font-size: 0.9rem; 
            font-style: italic;
        }
        .content {
            white-space: pre-line;
            font-size: 1.1rem;
            line-height: 1.8;
        }
        h2 { 
            color: #DAA520; 
            border-bottom: 1px solid #DAA520;
            padding-bottom: 0.3rem;
            margin-top: 2rem;
        }
        h3 { 
            color: #1e293b; 
            margin-top: 1.5rem;
        }
        ul, ol {
            margin: 1rem 0;
            padding-left: 2rem;
        }
        li {
            margin: 0.5rem 0;
        }
        .footer {
            margin-top: 3rem;
            padding-top: 1rem;
            border-top: 1px solid #e2e8f0;
            text-align: center;
            color: #64748b;
            font-size: 0.8rem;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>${report.title}</h1>
        <div class="meta">Generated on ${report.generatedAt.toLocaleDateString()} at ${report.generatedAt.toLocaleTimeString()}</div>
    </div>
    <div class="content">${this.formatContentAsHTML(report.content)}</div>
    <div class="footer">
        Generated by AGORA - The Eternal Space for Collective Wisdom
    </div>
</body>
</html>`;
    
    return new Blob([htmlContent], { type: 'text/html' });
  }

  static downloadFile(blob: Blob, filename: string, format: string) {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${filename}.${format}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  private static formatContentAsHTML(content: string): string {
    return content
      .replace(/^# (.*$)/gm, '<h2>$1</h2>')
      .replace(/^## (.*$)/gm, '<h3>$1</h3>')
      .replace(/^### (.*$)/gm, '<h4>$1</h4>')
      .replace(/^\- (.*$)/gm, '<li>$1</li>')
      .replace(/(<li>.*<\/li>)/s, '<ul>$1</ul>')
      .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>')
      .replace(/\n\n/g, '</p><p>')
      .replace(/^(?!<[hul])/gm, '<p>')
      .replace(/(?<!>)$/gm, '</p>');
  }
}
