export interface AlternativeExpert {
  id: string;
  name: string;
  era: string;
  eraType: 'pre' | 'post';
  category: string;
  categoryLabel: string;
  domain: string;
  description: string;
  quote: string;
  traits: {
    creativity: number;
    skepticism: number;
    optimism: number;
  };
  imageUrl: string;
}

export const MIND_CATEGORIES = [
  { id: 'philosophy', label: 'Philosophy & Ethics' },
  { id: 'science', label: 'Science & Natural Philosophy' },
  { id: 'arts', label: 'Arts & Creativity' },
  { id: 'mathematics', label: 'Mathematics & Logic' },
  { id: 'leadership', label: 'Leadership & Governance' },
  { id: 'innovation', label: 'Innovation & Technology' },
  { id: 'social', label: 'Social & Economic Thought' },
] as const;

export const alternativeMinds: AlternativeExpert[] = [
  // === PHILOSOPHY & ETHICS ===
  {
    id: 'aristotle',
    name: 'Aristotle',
    era: 'Ancient Greece (384–322 BC)',
    eraType: 'pre',
    category: 'philosophy',
    categoryLabel: 'Philosophy & Ethics',
    domain: 'Philosophy, Logic',
    description: 'Greek philosopher who systematized logic, ethics, and metaphysics. His works shaped Western intellectual tradition for millennia.',
    quote: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.',
    traits: { creativity: 70, skepticism: 75, optimism: 65 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Aristotle_Altemps_Inv8575.jpg',
  },
  {
    id: 'plato',
    name: 'Plato',
    era: 'Ancient Greece (428–348 BC)',
    eraType: 'pre',
    category: 'philosophy',
    categoryLabel: 'Philosophy & Ethics',
    domain: 'Philosophy, Metaphysics',
    description: 'Founder of the Academy in Athens. His Theory of Forms posits that abstract ideals are more real than the physical world.',
    quote: 'The measure of a man is what he does with power.',
    traits: { creativity: 85, skepticism: 65, optimism: 70 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Plato_Silanion_Musei_Capitolini_MC1377.jpg',
  },
  {
    id: 'marcus_aurelius',
    name: 'Marcus Aurelius',
    era: 'Roman Empire (121–180 AD)',
    eraType: 'pre',
    category: 'philosophy',
    categoryLabel: 'Philosophy & Ethics',
    domain: 'Stoic Philosophy, Governance',
    description: 'Roman emperor and Stoic philosopher. His Meditations remain a cornerstone of practical philosophy and self-discipline.',
    quote: 'The happiness of your life depends upon the quality of your thoughts.',
    traits: { creativity: 55, skepticism: 60, optimism: 50 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/MSR-ra-61-b-1-DM.jpg',
  },
  {
    id: 'aquinas',
    name: 'Thomas Aquinas',
    era: 'Medieval Europe (1225–1274)',
    eraType: 'pre',
    category: 'philosophy',
    categoryLabel: 'Philosophy & Ethics',
    domain: 'Theology, Scholastic Philosophy',
    description: 'Medieval scholastic theologian who synthesized Aristotelian philosophy with Christian theology, creating an enduring intellectual framework.',
    quote: 'To one who has faith, no explanation is necessary. To one without faith, no explanation is possible.',
    traits: { creativity: 60, skepticism: 70, optimism: 75 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e3/St-thomas-aquinas.jpg',
  },
  {
    id: 'kant',
    name: 'Immanuel Kant',
    era: 'Enlightenment (1724–1804)',
    eraType: 'post',
    category: 'philosophy',
    categoryLabel: 'Philosophy & Ethics',
    domain: 'Epistemology, Ethics',
    description: 'German philosopher whose Critique of Pure Reason and categorical imperative reshaped modern philosophy and moral reasoning.',
    quote: 'Act only according to that maxim whereby you can at the same time will that it should become a universal law.',
    traits: { creativity: 65, skepticism: 85, optimism: 55 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Kant_gemaelde_3.jpg',
  },
  {
    id: 'nietzsche',
    name: 'Friedrich Nietzsche',
    era: 'Modern (1844–1900)',
    eraType: 'post',
    category: 'philosophy',
    categoryLabel: 'Philosophy & Ethics',
    domain: 'Existentialism, Cultural Criticism',
    description: 'German philosopher who challenged conventional morality and championed individual greatness through the will to power.',
    quote: 'He who has a why to live can bear almost any how.',
    traits: { creativity: 95, skepticism: 90, optimism: 40 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/Nietzsche187a.jpg',
  },
  {
    id: 'de_beauvoir',
    name: 'Simone de Beauvoir',
    era: 'Modern (1908–1986)',
    eraType: 'post',
    category: 'philosophy',
    categoryLabel: 'Philosophy & Ethics',
    domain: 'Existentialism, Feminist Philosophy',
    description: 'French existentialist philosopher and author of The Second Sex, pioneering feminist theory and ethics of freedom.',
    quote: 'One is not born, but rather becomes, a woman.',
    traits: { creativity: 80, skepticism: 75, optimism: 65 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/09/Simone_de_Beauvoir2.png',
  },

  // === SCIENCE & NATURAL PHILOSOPHY ===
  {
    id: 'archimedes',
    name: 'Archimedes',
    era: 'Ancient Greece (287–212 BC)',
    eraType: 'pre',
    category: 'science',
    categoryLabel: 'Science & Natural Philosophy',
    domain: 'Mathematics, Physics, Engineering',
    description: 'Greek polymath who discovered the principles of buoyancy and the lever, and devised ingenious war machines.',
    quote: 'Give me a lever long enough and a fulcrum on which to place it, and I shall move the world.',
    traits: { creativity: 90, skepticism: 60, optimism: 80 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Domenico-Fetti_Archimedes_1620.jpg',
  },
  {
    id: 'galileo',
    name: 'Galileo Galilei',
    era: 'Renaissance (1564–1642)',
    eraType: 'pre',
    category: 'science',
    categoryLabel: 'Science & Natural Philosophy',
    domain: 'Astronomy, Physics',
    description: 'Father of modern observational astronomy and physics. Championed heliocentrism through telescope observations.',
    quote: 'And yet it moves.',
    traits: { creativity: 80, skepticism: 85, optimism: 70 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Justus_Sustermans_-_Portrait_of_Galileo_Galilei%2C_1636.jpg',
  },
  {
    id: 'newton',
    name: 'Isaac Newton',
    era: 'Early Modern (1643–1727)',
    eraType: 'pre',
    category: 'science',
    categoryLabel: 'Science & Natural Philosophy',
    domain: 'Physics, Mathematics, Optics',
    description: 'English polymath who formulated the laws of motion and universal gravitation, and co-invented calculus.',
    quote: 'If I have seen further, it is by standing on the shoulders of giants.',
    traits: { creativity: 85, skepticism: 80, optimism: 55 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Portrait_of_Sir_Isaac_Newton%2C_1689.jpg',
  },
  {
    id: 'ibn_al_haytham',
    name: 'Ibn al-Haytham',
    era: 'Islamic Golden Age (965–1040)',
    eraType: 'pre',
    category: 'science',
    categoryLabel: 'Science & Natural Philosophy',
    domain: 'Optics, Scientific Method',
    description: 'Arab polymath considered the father of modern optics. Pioneered the experimental scientific method centuries before the Enlightenment.',
    quote: 'The duty of the man who investigates the writings of scientists is not to believe, but rather to doubt.',
    traits: { creativity: 75, skepticism: 90, optimism: 65 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/63/Ibn_al-Haytham.png',
  },
  {
    id: 'darwin',
    name: 'Charles Darwin',
    era: 'Victorian Era (1809–1882)',
    eraType: 'post',
    category: 'science',
    categoryLabel: 'Science & Natural Philosophy',
    domain: 'Natural History, Evolution',
    description: 'English naturalist whose theory of evolution by natural selection revolutionized biology and our understanding of life.',
    quote: 'It is not the strongest of the species that survives, nor the most intelligent, but the one most responsive to change.',
    traits: { creativity: 75, skepticism: 80, optimism: 60 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Charles_Darwin_seated_crop.jpg',
  },
  {
    id: 'tesla',
    name: 'Nikola Tesla',
    era: 'Modern (1856–1943)',
    eraType: 'post',
    category: 'science',
    categoryLabel: 'Science & Natural Philosophy',
    domain: 'Electrical Engineering, Invention',
    description: 'Serbian-American inventor who pioneered alternating current, wireless communication, and envisioned a connected world.',
    quote: 'The present is theirs; the future, for which I really worked, is mine.',
    traits: { creativity: 100, skepticism: 45, optimism: 85 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/79/Tesla_circa_1890.jpeg',
  },
  {
    id: 'feynman',
    name: 'Richard Feynman',
    era: 'Modern (1918–1988)',
    eraType: 'post',
    category: 'science',
    categoryLabel: 'Science & Natural Philosophy',
    domain: 'Quantum Physics, Science Education',
    description: 'American theoretical physicist known for quantum electrodynamics and his extraordinary ability to explain complex science.',
    quote: 'I would rather have questions that can\'t be answered than answers that can\'t be questioned.',
    traits: { creativity: 90, skepticism: 70, optimism: 80 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/4/42/Richard_Feynman_Nobel.jpg',
  },

  // === ARTS & CREATIVITY ===
  {
    id: 'michelangelo',
    name: 'Michelangelo',
    era: 'Renaissance (1475–1564)',
    eraType: 'pre',
    category: 'arts',
    categoryLabel: 'Arts & Creativity',
    domain: 'Sculpture, Painting, Architecture',
    description: 'Italian Renaissance master whose works—the Sistine Chapel ceiling, David, the Pietà—defined artistic perfection.',
    quote: 'I saw the angel in the marble and carved until I set him free.',
    traits: { creativity: 100, skepticism: 55, optimism: 60 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Miguel_%C3%81ngel%2C_por_Daniele_da_Volterra_%28detalle%29.jpg',
  },
  {
    id: 'shakespeare',
    name: 'William Shakespeare',
    era: 'Elizabethan Era (1564–1616)',
    eraType: 'pre',
    category: 'arts',
    categoryLabel: 'Arts & Creativity',
    domain: 'Drama, Poetry, Literature',
    description: 'English playwright and poet whose works explore the full range of human emotion and remain the pinnacle of literary achievement.',
    quote: 'All the world\'s a stage, and all the men and women merely players.',
    traits: { creativity: 100, skepticism: 60, optimism: 65 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Shakespeare.jpg',
  },
  {
    id: 'bach',
    name: 'Johann Sebastian Bach',
    era: 'Baroque Period (1685–1750)',
    eraType: 'pre',
    category: 'arts',
    categoryLabel: 'Arts & Creativity',
    domain: 'Music Composition, Counterpoint',
    description: 'German Baroque composer whose mastery of counterpoint, harmony, and musical architecture remains unmatched.',
    quote: 'The aim and final end of all music should be none other than the glory of God and the refreshment of the soul.',
    traits: { creativity: 90, skepticism: 40, optimism: 80 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6a/Johann_Sebastian_Bach.jpg',
  },
  {
    id: 'murasaki',
    name: 'Murasaki Shikibu',
    era: 'Heian Japan (c. 978–1014)',
    eraType: 'pre',
    category: 'arts',
    categoryLabel: 'Arts & Creativity',
    domain: 'Literature, Psychology',
    description: 'Japanese novelist who wrote The Tale of Genji, widely considered the world\'s first novel and a masterpiece of psychological fiction.',
    quote: 'In this world nothing is permanent.',
    traits: { creativity: 90, skepticism: 55, optimism: 50 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3b/Murasaki_Shikibu_2.jpg',
  },
  {
    id: 'kahlo',
    name: 'Frida Kahlo',
    era: 'Modern (1907–1954)',
    eraType: 'post',
    category: 'arts',
    categoryLabel: 'Arts & Creativity',
    domain: 'Painting, Surrealism, Identity Art',
    description: 'Mexican painter whose deeply personal, symbolically rich self-portraits explore identity, pain, and the human condition.',
    quote: 'I paint myself because I am so often alone and because I am the subject I know best.',
    traits: { creativity: 95, skepticism: 50, optimism: 55 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/06/Frida_Kahlo%2C_by_Guillermo_Kahlo.jpg',
  },
  {
    id: 'picasso',
    name: 'Pablo Picasso',
    era: 'Modern (1881–1973)',
    eraType: 'post',
    category: 'arts',
    categoryLabel: 'Arts & Creativity',
    domain: 'Painting, Sculpture, Cubism',
    description: 'Spanish painter and sculptor who co-founded Cubism and constantly reinvented artistic expression across styles.',
    quote: 'Every child is an artist. The problem is how to remain an artist once we grow up.',
    traits: { creativity: 100, skepticism: 45, optimism: 75 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/98/Pablo_picasso_1.jpg',
  },
  {
    id: 'angelou',
    name: 'Maya Angelou',
    era: 'Modern (1928–2014)',
    eraType: 'post',
    category: 'arts',
    categoryLabel: 'Arts & Creativity',
    domain: 'Poetry, Memoir, Civil Rights',
    description: 'American poet, memoirist, and civil rights activist whose words gave voice to resilience and the beauty of the human spirit.',
    quote: 'There is no greater agony than bearing an untold story inside you.',
    traits: { creativity: 85, skepticism: 50, optimism: 85 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4f/Angelou_at_Clinton_inauguration_%28cropped%29.jpg',
  },

  // === MATHEMATICS & LOGIC ===
  {
    id: 'euclid',
    name: 'Euclid',
    era: 'Ancient Greece (c. 300 BC)',
    eraType: 'pre',
    category: 'mathematics',
    categoryLabel: 'Mathematics & Logic',
    domain: 'Geometry, Axiomatic Systems',
    description: 'Father of geometry whose Elements remained the standard mathematical textbook for over two thousand years.',
    quote: 'There is no royal road to geometry.',
    traits: { creativity: 60, skepticism: 80, optimism: 65 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Euklid-von-Alexandria_1.jpg',
  },
  {
    id: 'al_khwarizmi',
    name: 'Al-Khwarizmi',
    era: 'Islamic Golden Age (c. 780–850)',
    eraType: 'pre',
    category: 'mathematics',
    categoryLabel: 'Mathematics & Logic',
    domain: 'Algebra, Astronomy',
    description: 'Persian mathematician whose name gave us the word "algorithm" and whose work founded the discipline of algebra.',
    quote: 'That fondness for science... that affability and condescension which God shows to the learned.',
    traits: { creativity: 75, skepticism: 65, optimism: 80 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Al-Khwarizmi_portrait.jpg',
  },
  {
    id: 'fibonacci',
    name: 'Fibonacci',
    era: 'Medieval Italy (c. 1170–1250)',
    eraType: 'pre',
    category: 'mathematics',
    categoryLabel: 'Mathematics & Logic',
    domain: 'Number Theory, Trade Mathematics',
    description: 'Italian mathematician who introduced Hindu-Arabic numerals to Europe and discovered the famous Fibonacci sequence in nature.',
    quote: 'If by chance I have omitted anything, I submit it to your correction.',
    traits: { creativity: 70, skepticism: 55, optimism: 75 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Fibonacci2.jpg',
  },
  {
    id: 'descartes',
    name: 'René Descartes',
    era: 'Early Modern (1596–1650)',
    eraType: 'pre',
    category: 'mathematics',
    categoryLabel: 'Mathematics & Logic',
    domain: 'Analytical Geometry, Philosophy',
    description: 'French philosopher and mathematician who bridged algebra and geometry, and founded modern rationalist philosophy.',
    quote: 'I think, therefore I am.',
    traits: { creativity: 80, skepticism: 90, optimism: 55 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/73/Frans_Hals_-_Portret_van_Ren%C3%A9_Descartes.jpg',
  },
  {
    id: 'gauss',
    name: 'Carl Friedrich Gauss',
    era: 'Modern (1777–1855)',
    eraType: 'post',
    category: 'mathematics',
    categoryLabel: 'Mathematics & Logic',
    domain: 'Number Theory, Statistics',
    description: 'The "Prince of Mathematicians" who made groundbreaking contributions to number theory, statistics, and differential geometry.',
    quote: 'Mathematics is the queen of the sciences, and number theory is the queen of mathematics.',
    traits: { creativity: 85, skepticism: 75, optimism: 60 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Carl_Friedrich_Gauss_1840_by_Jensen.jpg',
  },
  {
    id: 'turing',
    name: 'Alan Turing',
    era: 'Modern (1912–1954)',
    eraType: 'post',
    category: 'mathematics',
    categoryLabel: 'Mathematics & Logic',
    domain: 'Computer Science, Cryptography',
    description: 'British mathematician who formalized the concept of computation and cracked the Enigma code, laying foundations for modern computing.',
    quote: 'We can only see a short distance ahead, but we can see plenty there that needs to be done.',
    traits: { creativity: 90, skepticism: 65, optimism: 70 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a1/Alan_Turing_Aged_16.jpg',
  },
  {
    id: 'noether',
    name: 'Emmy Noether',
    era: 'Modern (1882–1935)',
    eraType: 'post',
    category: 'mathematics',
    categoryLabel: 'Mathematics & Logic',
    domain: 'Abstract Algebra, Theoretical Physics',
    description: 'German mathematician whose theorem connecting symmetry and conservation laws is fundamental to modern physics.',
    quote: 'My methods are really methods of working and thinking; this is why they have crept in everywhere anonymously.',
    traits: { creativity: 85, skepticism: 70, optimism: 75 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e5/Noether.jpg',
  },

  // === LEADERSHIP & GOVERNANCE ===
  {
    id: 'sun_tzu',
    name: 'Sun Tzu',
    era: 'Ancient China (544–496 BC)',
    eraType: 'pre',
    category: 'leadership',
    categoryLabel: 'Leadership & Governance',
    domain: 'Military Strategy, Leadership',
    description: 'Chinese military strategist whose Art of War remains the most influential treatise on strategy and conflict resolution.',
    quote: 'The supreme art of war is to subdue the enemy without fighting.',
    traits: { creativity: 80, skepticism: 85, optimism: 45 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/37/Erta_Sunzi.jpg',
  },
  {
    id: 'cleopatra',
    name: 'Cleopatra VII',
    era: 'Ptolemaic Egypt (69–30 BC)',
    eraType: 'pre',
    category: 'leadership',
    categoryLabel: 'Leadership & Governance',
    domain: 'Diplomacy, Statecraft',
    description: 'Last active ruler of Ptolemaic Egypt, a brilliant linguist and diplomat who navigated complex geopolitical alliances.',
    quote: 'I will not be triumphed over.',
    traits: { creativity: 75, skepticism: 70, optimism: 65 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Kleopatra-VII.-Altes-Museum-Berlin1.jpg',
  },
  {
    id: 'elizabeth_i',
    name: 'Elizabeth I',
    era: 'Tudor England (1533–1603)',
    eraType: 'pre',
    category: 'leadership',
    categoryLabel: 'Leadership & Governance',
    domain: 'Statecraft, Cultural Patronage',
    description: 'The Virgin Queen who transformed England into a major world power through shrewd politics and cultural patronage.',
    quote: 'I know I have the body of a weak and feeble woman, but I have the heart and stomach of a king.',
    traits: { creativity: 70, skepticism: 80, optimism: 60 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/af/Darnley_stage_3.jpg',
  },
  {
    id: 'genghis_khan',
    name: 'Genghis Khan',
    era: 'Medieval Mongolia (1162–1227)',
    eraType: 'pre',
    category: 'leadership',
    categoryLabel: 'Leadership & Governance',
    domain: 'Empire Building, Military Organization',
    description: 'Founder of the Mongol Empire, the largest contiguous land empire in history. Master of logistics and meritocratic leadership.',
    quote: 'If you are afraid, do not do it. If you are doing it, do not be afraid.',
    traits: { creativity: 75, skepticism: 65, optimism: 70 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/35/YuanEmperorAlbumGenghisPortrait.jpg',
  },
  {
    id: 'lincoln',
    name: 'Abraham Lincoln',
    era: 'Modern (1809–1865)',
    eraType: 'post',
    category: 'leadership',
    categoryLabel: 'Leadership & Governance',
    domain: 'Democratic Leadership, Unity',
    description: 'The 16th U.S. President who preserved the Union and abolished slavery, embodying moral leadership through crisis.',
    quote: 'The best way to predict the future is to create it.',
    traits: { creativity: 65, skepticism: 60, optimism: 75 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ab/Abraham_Lincoln_O-77_matte_collodion_print.jpg',
  },
  {
    id: 'gandhi',
    name: 'Mahatma Gandhi',
    era: 'Modern (1869–1948)',
    eraType: 'post',
    category: 'leadership',
    categoryLabel: 'Leadership & Governance',
    domain: 'Nonviolent Resistance, Social Justice',
    description: 'Indian leader who pioneered nonviolent civil disobedience, inspiring movements for civil rights and freedom worldwide.',
    quote: 'Be the change you wish to see in the world.',
    traits: { creativity: 70, skepticism: 55, optimism: 90 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7a/Mahatma-Gandhi%2C_studio%2C_1931.jpg',
  },
  {
    id: 'mandela',
    name: 'Nelson Mandela',
    era: 'Modern (1918–2013)',
    eraType: 'post',
    category: 'leadership',
    categoryLabel: 'Leadership & Governance',
    domain: 'Reconciliation, Human Rights',
    description: 'South African anti-apartheid leader who became a symbol of forgiveness and reconciliation after 27 years of imprisonment.',
    quote: 'It always seems impossible until it is done.',
    traits: { creativity: 65, skepticism: 50, optimism: 90 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/02/Nelson_Mandela_1994.jpg',
  },

  // === INNOVATION & TECHNOLOGY ===
  {
    id: 'zhang_heng',
    name: 'Zhang Heng',
    era: 'Han Dynasty (78–139 AD)',
    eraType: 'pre',
    category: 'innovation',
    categoryLabel: 'Innovation & Technology',
    domain: 'Astronomy, Seismology, Engineering',
    description: 'Chinese polymath who invented the first seismoscope and made foundational contributions to astronomy and cartography.',
    quote: 'The sun is like fire and the moon is like water.',
    traits: { creativity: 85, skepticism: 60, optimism: 75 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/09/Zhang_Heng.jpg',
  },
  {
    id: 'al_jazari',
    name: 'Ismail al-Jazari',
    era: 'Medieval Mesopotamia (1136–1206)',
    eraType: 'pre',
    category: 'innovation',
    categoryLabel: 'Innovation & Technology',
    domain: 'Mechanical Engineering, Automata',
    description: 'Arab polymath and father of robotics who created programmable automata and pioneered mechanical engineering concepts.',
    quote: 'Design proceeds from need.',
    traits: { creativity: 95, skepticism: 50, optimism: 80 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/51/Al-Jazari_Automata_1205.jpg',
  },
  {
    id: 'gutenberg',
    name: 'Johannes Gutenberg',
    era: 'Late Medieval Europe (c. 1400–1468)',
    eraType: 'pre',
    category: 'innovation',
    categoryLabel: 'Innovation & Technology',
    domain: 'Printing, Information Technology',
    description: 'German inventor of the movable-type printing press, which democratized knowledge and ignited the Information Age.',
    quote: 'It is a press, certainly, but a press from which shall flow inexhaustible streams of the most abundant knowledge.',
    traits: { creativity: 85, skepticism: 55, optimism: 80 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/33/Gutenberg.jpg',
  },
  {
    id: 'archimedes_inv',
    name: 'Archimedes (Inventor)',
    era: 'Ancient Greece (287–212 BC)',
    eraType: 'pre',
    category: 'innovation',
    categoryLabel: 'Innovation & Technology',
    domain: 'Mechanical Devices, Engineering',
    description: 'Greek inventor of the screw pump, compound pulleys, and war machines. Bridged theoretical mathematics and practical invention.',
    quote: 'Eureka! I have found it!',
    traits: { creativity: 90, skepticism: 60, optimism: 80 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Domenico-Fetti_Archimedes_1620.jpg',
  },
  {
    id: 'edison',
    name: 'Thomas Edison',
    era: 'Modern (1847–1931)',
    eraType: 'post',
    category: 'innovation',
    categoryLabel: 'Innovation & Technology',
    domain: 'Practical Invention, Industrial R&D',
    description: 'America\'s most prolific inventor who industrialized the research process and gave the world electric light and sound recording.',
    quote: 'I have not failed. I have just found 10,000 ways that won\'t work.',
    traits: { creativity: 80, skepticism: 55, optimism: 85 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Thomas_Edison2.jpg',
  },
  {
    id: 'hopper',
    name: 'Grace Hopper',
    era: 'Modern (1906–1992)',
    eraType: 'post',
    category: 'innovation',
    categoryLabel: 'Innovation & Technology',
    domain: 'Computer Science, Programming',
    description: 'American computer scientist who invented the first compiler and championed machine-independent programming languages.',
    quote: 'The most dangerous phrase in the language is: We have always done it this way.',
    traits: { creativity: 85, skepticism: 60, optimism: 85 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Commodore_Grace_M._Hopper%2C_USN_%28covered%29.jpg',
  },
  {
    id: 'jobs',
    name: 'Steve Jobs',
    era: 'Modern (1955–2011)',
    eraType: 'post',
    category: 'innovation',
    categoryLabel: 'Innovation & Technology',
    domain: 'Design Innovation, Entrepreneurship',
    description: 'Co-founder of Apple who revolutionized personal computing, music, and mobile phones through design-driven innovation.',
    quote: 'Stay hungry, stay foolish.',
    traits: { creativity: 95, skepticism: 70, optimism: 80 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/dc/Steve_Jobs_Headshot_2010-CROP_%28cropped_2%29.jpg',
  },

  // === SOCIAL & ECONOMIC THOUGHT ===
  {
    id: 'ibn_khaldun',
    name: 'Ibn Khaldun',
    era: 'Medieval North Africa (1332–1406)',
    eraType: 'pre',
    category: 'social',
    categoryLabel: 'Social & Economic Thought',
    domain: 'Historiography, Social Theory',
    description: 'Arab historian and father of sociology who developed theories of social cohesion, rise and fall of civilizations.',
    quote: 'History is a discipline with diverse approaches and numerous pathways.',
    traits: { creativity: 75, skepticism: 80, optimism: 55 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/80/Bust_of_Ibn_Khaldun_%28Casbah_of_Bejaia%2C_Algeria%29.jpg',
  },
  {
    id: 'locke',
    name: 'John Locke',
    era: 'Early Modern (1632–1704)',
    eraType: 'pre',
    category: 'social',
    categoryLabel: 'Social & Economic Thought',
    domain: 'Liberalism, Political Philosophy',
    description: 'English philosopher whose ideas on natural rights, government by consent, and religious toleration shaped modern democracy.',
    quote: 'The end of law is not to abolish or restrain, but to preserve and enlarge freedom.',
    traits: { creativity: 65, skepticism: 70, optimism: 75 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d1/JohnLocke.png',
  },
  {
    id: 'adam_smith',
    name: 'Adam Smith',
    era: 'Enlightenment (1723–1790)',
    eraType: 'pre',
    category: 'social',
    categoryLabel: 'Social & Economic Thought',
    domain: 'Economics, Moral Philosophy',
    description: 'Scottish economist and philosopher whose Wealth of Nations laid the foundations for classical free-market economics.',
    quote: 'It is not from the benevolence of the butcher, the brewer, or the baker that we expect our dinner.',
    traits: { creativity: 70, skepticism: 65, optimism: 70 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/AdamSmith.jpg',
  },
  {
    id: 'wollstonecraft',
    name: 'Mary Wollstonecraft',
    era: 'Enlightenment (1759–1797)',
    eraType: 'pre',
    category: 'social',
    categoryLabel: 'Social & Economic Thought',
    domain: 'Feminism, Education, Rights',
    description: 'English writer and philosopher who wrote A Vindication of the Rights of Woman, pioneering feminist thought.',
    quote: 'I do not wish women to have power over men, but over themselves.',
    traits: { creativity: 75, skepticism: 70, optimism: 70 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/36/Mary_Wollstonecraft_by_John_Opie_%28c._1797%29.jpg',
  },
  {
    id: 'marx',
    name: 'Karl Marx',
    era: 'Modern (1818–1883)',
    eraType: 'post',
    category: 'social',
    categoryLabel: 'Social & Economic Thought',
    domain: 'Political Economy, Social Theory',
    description: 'German philosopher whose analysis of capitalism, class struggle, and historical materialism transformed political and economic thought.',
    quote: 'The philosophers have only interpreted the world, in various ways; the point is to change it.',
    traits: { creativity: 80, skepticism: 90, optimism: 50 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Karl_Marx_001.jpg',
  },
  {
    id: 'keynes',
    name: 'John Maynard Keynes',
    era: 'Modern (1883–1946)',
    eraType: 'post',
    category: 'social',
    categoryLabel: 'Social & Economic Thought',
    domain: 'Macroeconomics, Public Policy',
    description: 'British economist whose ideas on government spending and demand-side economics reshaped fiscal policy worldwide.',
    quote: 'The difficulty lies not so much in developing new ideas as in escaping from old ones.',
    traits: { creativity: 75, skepticism: 65, optimism: 70 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/John_Maynard_Keynes.jpg',
  },
  {
    id: 'arendt',
    name: 'Hannah Arendt',
    era: 'Modern (1906–1975)',
    eraType: 'post',
    category: 'social',
    categoryLabel: 'Social & Economic Thought',
    domain: 'Political Theory, Philosophy',
    description: 'German-American political theorist who explored totalitarianism, the nature of power, and "the banality of evil."',
    quote: 'The sad truth is that most evil is done by people who never make up their minds to be good or evil.',
    traits: { creativity: 80, skepticism: 85, optimism: 50 },
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Hannah_Arendt_1975_%28cropped%29.jpg',
  },
];

/** Get all alternative minds for a given category */
export function getMindsByCategory(category: string): AlternativeExpert[] {
  return alternativeMinds.filter(m => m.category === category);
}

/** Get a single mind by ID */
export function getAlternativeMindById(id: string): AlternativeExpert | undefined {
  return alternativeMinds.find(m => m.id === id);
}
