
import React, { useState, useMemo, useCallback } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { DiscussionMessage } from '@/services/aiOrchestrator';
import { FileGenerator } from '@/services/fileGenerator';
import { useToast } from "@/hooks/use-toast";
import { ErrorBoundary } from "@/components/ui/ErrorBoundary";
import { usePerformanceMonitor } from "@/hooks/usePerformanceMonitor";
import BrandedReportHeader from '@/components/reports/BrandedReportHeader';
import AnalyticsDashboard from '@/components/analytics/AnalyticsDashboard';
import { AIConfigurationPanel } from '@/components/reports/AIConfigurationPanel';
import { useReportAIConfig } from '@/hooks/useReportAIConfig';
import { ExpertConfig } from '@/components/ExpertCardList';
import { useReportGeneration } from '@/hooks/useReportGeneration';
import { ReportStatsGrid } from '@/components/reports/ReportStatsGrid';
import { ReportCard } from '@/components/reports/ReportCard';
import { ReportPreviewSection } from '@/components/reports/ReportPreviewSection';
import { REPORT_TYPES } from '@/components/reports/reportTypes';

interface ReportsModuleProps {
  discussionMessages?: DiscussionMessage[];
  challenge?: string;
  isDiscussionComplete?: boolean;
  experts?: ExpertConfig[];
  currentRound?: number;
  maxRounds?: number;
}

const ReportsModule = React.memo<ReportsModuleProps>(({
  discussionMessages = [],
  challenge = 'Sample Challenge',
  isDiscussionComplete = false,
  experts = [],
  currentRound = 0,
  maxRounds = 5
}) => {
  usePerformanceMonitor('ReportsModule', 100);
  const { toast } = useToast();
  const [activeTab, setActiveTab] = useState('overview');

  // Use the AI configuration hook
  const {
    useExpertConfig,
    setUseExpertConfig,
    manualProvider,
    setManualProvider,
    manualModel,
    setManualModel,
    manualApiKeys,
    updateManualApiKey,
    expertAIAnalysis,
    getFinalConfig
  } = useReportAIConfig(experts);

  // Use the report generation hook
  const {
    generatingReports,
    reportStatuses,
    generatedReports,
    generateAllReports,
    completedReportsCount,
    canGenerate
  } = useReportGeneration(discussionMessages, challenge, isDiscussionComplete);

  // Memoized calculations
  const uniqueExpertCount = useMemo(() => 
    new Set(discussionMessages.map(m => m.speaker)).size, 
    [discussionMessages]
  );

  // Enhanced download function with format-specific content preparation
  const downloadReport = useCallback(async (reportId: string, format: 'pdf' | 'html') => {
    const report = generatedReports[reportId];
    if (!report) {
      toast({
        title: "Report Not Available",
        description: "This report hasn't been generated yet.",
        variant: "destructive"
      });
      return;
    }

    try {
      let enhancedReport: typeof report;

      if (format === 'pdf') {
        // Create PDF-specific content with simple text branding
        const pdfBranding = FileGenerator.createPDFBrandingContent(
          report.title,
          report.generatedAt,
          uniqueExpertCount,
          discussionMessages.length,
          challenge
        );

        enhancedReport = {
          ...report,
          content: pdfBranding + report.content + '\n\n' + 
                   '--------------------\n' +
                   'Generated by AGORA - Collective Minds & Wisdom Platform\n' +
                   'Powered by AI Expert Collaboration Technology'
        };
      } else {
        // Create HTML-specific content with rich formatting
        const htmlBranding = FileGenerator.createHTMLBrandingContent(
          report.title,
          report.generatedAt,
          uniqueExpertCount,
          discussionMessages.length,
          challenge
        );

        enhancedReport = {
          ...report,
          content: htmlBranding + report.content + 
                   '<div style="margin-top: 40px; padding: 20px; background: #f8fafc; border-radius: 8px; text-align: center; font-size: 12px; color: #64748b;">' +
                   '<p style="margin: 0;">Generated by AGORA - Collective Minds & Wisdom Platform</p>' +
                   '<p style="margin: 5px 0 0 0;">Powered by AI Expert Collaboration Technology</p>' +
                   '</div>'
        };
      }

      let blob: Blob;
      if (format === 'pdf') {
        blob = await FileGenerator.generatePDF(enhancedReport);
      } else {
        blob = await FileGenerator.generateHTML(enhancedReport);
      }

      const filename = `AGORA_${report.title.replace(/[^a-zA-Z0-9]/g, '_')}_${new Date().toISOString().split('T')[0]}`;
      FileGenerator.downloadFile(blob, filename, format);

      toast({
        title: "Download Started",
        description: `${report.title} is being downloaded as ${format.toUpperCase()}.`
      });
    } catch (error) {
      console.error(`💥 Error downloading report:`, error);
      toast({
        title: "Download Error",
        description: "Could not download the report. Please try again.",
        variant: "destructive"
      });
    }
  }, [generatedReports, discussionMessages, challenge, toast, uniqueExpertCount]);

  return (
    <ErrorBoundary>
      <div className="space-y-6">
        {/* Enhanced Header with Branding */}
        <div className="bg-gradient-to-r from-indigo-600 to-purple-600 rounded-2xl shadow-lg border border-indigo-100 p-6 text-white">
          <BrandedReportHeader 
            title="Comprehensive Reports" 
            subtitle="AI-generated insights from expert discussions" 
            generatedAt={new Date()} 
            expertCount={uniqueExpertCount} 
            messageCount={discussionMessages.length} 
          />
          
          <div className="mt-6 flex flex-col gap-3">
            <Button 
              onClick={() => generateAllReports(getFinalConfig)} 
              disabled={!canGenerate} 
              className="bg-white text-indigo-600 hover:bg-indigo-50 disabled:opacity-50 w-full"
            >
              {generatingReports ? 'Generating AI-Enhanced Reports...' : 'Generate All Reports with AI'}
            </Button>
          </div>
        </div>

        {/* Enhanced Tabs with AI Configuration */}
        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList className="grid w-full grid-cols-4">
            <TabsTrigger value="overview">Reports Overview</TabsTrigger>
            <TabsTrigger value="ai-config">AI Configuration</TabsTrigger>
            <TabsTrigger value="analytics">Analytics Dashboard</TabsTrigger>
            <TabsTrigger value="preview">Report Preview</TabsTrigger>
          </TabsList>

          <TabsContent value="ai-config" className="space-y-6">
            <AIConfigurationPanel
              useExpertConfig={useExpertConfig}
              setUseExpertConfig={setUseExpertConfig}
              manualProvider={manualProvider}
              setManualProvider={setManualProvider}
              manualModel={manualModel}
              setManualModel={setManualModel}
              manualApiKeys={manualApiKeys}
              updateManualApiKey={updateManualApiKey}
              expertAIAnalysis={expertAIAnalysis}
              experts={experts}
            />
          </TabsContent>

          <TabsContent value="overview" className="space-y-6">
            {!isDiscussionComplete && (
              <div className="mb-4 p-4 bg-amber-50 border border-amber-200 rounded-lg">
                <p className="text-amber-800 text-sm">
                  Reports will be available after completing a discussion with experts.
                </p>
              </div>
            )}

            {/* Stats Grid */}
            <ReportStatsGrid 
              completedReportsCount={completedReportsCount}
              messageCount={discussionMessages.length}
              uniqueExpertCount={uniqueExpertCount}
            />

            {/* Reports Grid */}
            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-4">
              {REPORT_TYPES.map(report => (
                <ReportCard
                  key={report.id}
                  report={report}
                  status={reportStatuses[report.id] || 'pending'}
                  reportData={generatedReports[report.id]}
                  onDownload={downloadReport}
                />
              ))}
            </div>
          </TabsContent>

          <TabsContent value="analytics">
            <AnalyticsDashboard 
              messages={discussionMessages} 
              experts={experts} 
              currentRound={currentRound} 
              maxRounds={maxRounds} 
            />
          </TabsContent>

          <TabsContent value="preview">
            <ReportPreviewSection
              generatedReports={generatedReports}
              completedReportsCount={completedReportsCount}
              uniqueExpertCount={uniqueExpertCount}
              messageCount={discussionMessages.length}
            />
          </TabsContent>
        </Tabs>
      </div>
    </ErrorBoundary>
  );
});

ReportsModule.displayName = 'ReportsModule';
export default ReportsModule;
